name: Exemplo de Workflow

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir mensagem
        run: echo "Hello World!"

  windows:
    runs-on: windows-latest
    steps:
      - name: Imprimir mensagem
        run: echo "Hello World!"

  macos:
    runs-on: macos-latest
    steps:
      - name: Imprimir mensagem
        run: echo "Hello World!"

  final:
    needs: [linux, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir mensagem
        run: echo "Finalizado!"


